example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
# TODO: Implement Routings Here
from django.urls import path
from example_app.views import index
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

mywatchlist/urls.py
from django.urls import path
from mywatchlist.views import show_watchlist
from mywatchlist.views import show_xml
from mywatchlist.views import show_json
from mywatchlist.views import show_xml_by_id
from mywatchlist.views import show_json_by_id


app_name = 'mywatchlist'

urlpatterns = [
    path('', show_watchlist, name='show_watchlist'),
    path('html/', show_watchlist, name='show_watchlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('xml/<int:id>', show_xml_by_id, name='show_xml_by_id'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

# TODO: Implement Routings Here

todolist/urls.py
from django.urls import path
from todolist.views import create_task, delete_task, show_todolist, update_task, get_todo_json
from todolist.views import register
from todolist.views import login_user
from todolist.views import logout_user


app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create-task/', create_task, name='create_task'),
    path('json/', get_todo_json, name='get_todo_json'),
    path('update_task/<int:id>', update_task, name='update_task'),
    path('delete_task/<int:id>', delete_task, name='delete_task'),
]

example_app/models.py
from django.db import models

# Create your models here.

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField()

mywatchlist/models.py
from django.db import models

# Create your models here.
class MyWatchlist(models.Model):
    watched = models.BooleanField(default=False)
    title = models.CharField(max_length=255)
    rating = models.FloatField()
    release_date = models.CharField(max_length=255)
    review = models.TextField()

todolist/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField()
    title = models.CharField(max_length=255)
    description = models.TextField()
    is_finished = models.BooleanField(default=False)

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

katalog/views.py
from django.shortcuts import render
from katalog.models import CatalogItem

# TODO: Create your views here.

def show_katalog(request):
    data_barang_katalog = CatalogItem.objects.all()
    context = { 
        'list_item': data_barang_katalog,
        'nama': 'Vladi Jingga Mentari',
        'student_id': '2106635631'
    }
    return render(request, "katalog.html", context)

mywatchlist/views.py
from django.shortcuts import render
from mywatchlist.models import MyWatchlist
from django.http import HttpResponse
from django.core import serializers

# Create your views here.
def show_watchlist(request):
    data_watchlist = MyWatchlist.objects.all()
    is_watched = 0
    not_watched = 0
    for a in data_watchlist:
        if a.watched:
            is_watched += 1
        else:
            not_watched += 1
    context = { 
        'list_item': data_watchlist,
        'nama': 'Vladi Jingga Mentari',
        'student_id': '2106635631',
        'x': is_watched,
        'y': not_watched,
    }
    return render(request, "mywatchlist.html", context)

def show_xml(request):
    data = MyWatchlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = MyWatchlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request,id):
    data = MyWatchlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = MyWatchlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

todolist/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from todolist.models import Task
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.core import serializers
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

# Create your views here.


@login_required(login_url='/todolist/login/')
def show_todolist(request):
    context = {
        'user': request.user,
    }
    return render(request, 'todolist.html', context)


def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')

    context = {'form': form}
    return render(request, 'register.html', context)


def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)  # melakukan login terlebih dahulu
            response = HttpResponseRedirect(
                reverse("todolist:show_todolist"))  # membuat response
            # membuat cookie last_login dan menambahkannya ke dalam response
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)


def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response


@csrf_exempt
@login_required(login_url='/todolist/login/')
def create_task(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        todo = Task.objects.create(
            user=request.user,
            title=title,
            description=description,
            is_finished=False,
            date=datetime.datetime.now())
        return JsonResponse(
            {
                'pk': todo.id,
                'fields': {
                    'title': todo.title,
                    'description': todo.description,
                    'is_finished': todo.is_finished,
                    'date': todo.date,
                },
            },
            status=200,
        )

@login_required(login_url='/todolist/login/')
def update_task(request, id):
    todo = Task.objects.get(user=request.user, id=id)
    todo.is_finished = not todo.is_finished
    todo.save()
    return redirect('todolist:show_todolist')


@login_required(login_url='/todolist/login/')
def delete_task(request, id):
    todo = Task.objects.get(user=request.user, id=id)
    todo.delete()
    return redirect('todolist:show_todolist')


@login_required(login_url='/todolist/login/')
def get_todo_json(request):
    todo = Task.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", todo), content_type="application/json")

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

katalog/templates/katalog.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Lab 1 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{student_id}}</p>

  <table>
    <tr>
      <th>Item Name</th>
      <th>Item Price</th>
      <th>Item Stock</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Item URL</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for item in list_item %}
    <tr>
        <th>{{item.item_name}}</th>
        <th>{{item.item_price}}</th>
        <th>{{item.item_stock}}</th>
        <th>{{item.rating}}</th>
        <th>{{item.description}}</th>
        <th>{{item.item_url}}</th>
    </tr>
    {% endfor %}
  </table>

 {% endblock content %}

mywatchlist/templates/mywatchlist.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Assignment 3 PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{student_id}}</p>

  <table>
    <tr>
      <th>Watched</th>
      <th>Title</th>
      <th>Rating</th>
      <th>Release Date</th>
      <th>Review</th>

    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for item in list_item %}
    <tr>
        <th>
            {% if item.watched %}
            <p></p>
            {% else %}
            <img src="https://cdn.discordapp.com/attachments/1009760771451912235/1022026158428135444/unknown_3.png"/>
            {% endif %}
          </th>
        <th>{{item.title}}</th>
        <th>{{item.rating}}</th>
        <th>{{item.release_date}}</th>
        <th>{{item.review}}</th>
    </tr>
    {% endfor %}
    {% if x >= y %}
    <p>Selamat, kamu sudah banyak menonton!!</p>
    {% else %}
    <p>Wah, kamu masih sedikit menonton!</p>
    {% endif %}
  </table>

 {% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
        
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    {% block meta %}
    {% endblock meta %}
</head>
<style>
    body {
        background-color: rgb(0, 0, 0);
        background-image:
            radial-gradient(at 78% 0%, rgb(110, 101, 89) 0px, transparent 50%),
            radial-gradient(at 100% 90%, rgb(155, 80, 104) 0px, transparent 50%),
            radial-gradient(at 55% 5%, rgb(0, 0, 0) 0px, transparent 50%),
            radial-gradient(at 97% 92%, rgb(70, 16, 54) 0px, transparent 50%),
            radial-gradient(at 95% 0%, rgb(0, 8, 97) 0px, transparent 50%),
            radial-gradient(at 9% 95%, rgb(8, 28, 24) 0px, transparent 50%),
            radial-gradient(at 49% 84%, rgb(140, 102, 49) 0px, transparent 50%);
        background-repeat: no-repeat;
        background-attachment: fixed;
    }

    .bg-modal-fade {
        background-color: rgb(0, 0, 0, 0.15);
        backdrop-filter: blur(9px);
        -webkit-backdrop-filter: blur(9px);
    }

    .bg-glass {
        background: rgba(255, 255, 255, 0.15) !important;
        /* box-shadow: 0 8px 32px 0 rgba(32, 21, 35, 0.37); */
        backdrop-filter: blur(9px);
        -webkit-backdrop-filter: blur(9px);
        border-radius: 10px;
        border: 1px solid rgba(255, 255, 255, 0.18);
        transition: 0.2s;

    }

    .card-todo {
        background: rgba(255, 255, 255, 0.15) !important;
        /* box-shadow: 0 8px 32px 0 rgba(32, 21, 35, 0.37); */
        backdrop-filter: blur(9px);
        -webkit-backdrop-filter: blur(9px);
        border-radius: 10px;
        border: 1px solid rgba(255, 255, 255, 0.18);
        padding: -0.5;
        min-width: 20rem;
        max-width: 30rem;
        transition: 0.2s;

    }

    .card-todo:hover {
        box-shadow: 0 8px 32px 0 rgba(147, 137, 150, 0.37);
    }

    .navbar-brand {
        transition: 0.2s;
    }

    .navbar-brand:hover {
        color: white !important;
        text-decoration: underline;
        text-shadow: 0px 2px 9px rgba(255, 246, 251, 0.50);
    }

    .bg-glass:hover {
        box-shadow: 0 8px 32px 0 rgba(32, 21, 35, 0.37);
    }

    .custom-title {
        font-size: 100px;
        color: rgba(255, 255, 255, .5);
        line-height: 90%;

    }

    .form-outline {
        border: none !important;
        background-color: none !important;
        color: white;
        border-bottom: 2px solid white;

    }

    .link-primary {
        color: white !important;
        font-weight: 700;
        text-decoration: none;
        transition: 0.2s;
    }

    .link-primary:hover {
        color: white !important;
        text-decoration: underline;
        text-shadow: 0px 2px 9px rgba(255, 246, 251, 0.50);

    }
</style>

<body>
    {% block content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
        crossorigin="anonymous"></script>
    {% endblock content %}
</body>

</html>

todolist/templates/create_task.html
{% extends 'base.html' %}

{% block meta %}
<title>Add a New Task</title>
{% endblock meta %}

{% block content %}
<body>
<div class="task">
    <section class="vh-100 gradient-custom">
        <div class="container h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <nav class="navbar-dark">
                    <div class="container-fluid">
                      <a class="navbar-brand" href="{% url 'todolist:show_todolist' %}">&#8592 Go Back</a>
                    </div>
                  </nav>  
                <div class="col-12 col-md-3 col-lg-6 col-xl-5">
                    <h1 class="custom-title">what are you up to?</h1>
                    <div class="card bg-glass text-white" style="border-radius: 1rem;">
                        <div class="card-body p-5 text-center">
                            <form method="POST" action="">
                                {% csrf_token %}
                                <div class="mb-md-5">
                                    <p class="text-white-50 mb-md-4">stay <u>organized</u>, add a new to-do. </p>

                                    <div class="form mb-4">
                                        <input type="text" name="title" placeholder="Task" class="form-control">
                                    </div>

                                    <div class="form mb-4">
                                        <textarea type="text" name="description" placeholder="Description"
                                            class="form-control"></textarea>
                                    </div>
                                </div>
                                <button class="btn btn-outline-light btn-lg px-3" type="submit" value="Create Task">+
                                    Add</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    </body>

    {% if messages %}
    <ul>
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

</div>

{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}
<section class="vh-100 gradient-custom">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                <div class="card bg-glass text-white" style="border-radius: 1rem;">
                    <div class="card-body p-5 text-center">
                        <form method="POST" action="">
                            {% csrf_token %}

                        <div class="mb-md-5 mt-md-2 pb-5">
                            <h1 class="custom-title"> to-do; </h1>
                            <p class="text-white-50 mb-md-4">login or register to proceed</p>

                            <div class="form mb-4">
                                <input type="text" name="username" placeholder="Username" class="form-control">
                            </div>

                            <div class="form mb-4 mt-md-2">
                                <input type="password" name="password" placeholder="Password" class="form-control">
                            </div>
                            <button class="btn btn-outline-light btn-lg px-5" type="submit">Login</button>

                        </div>
                        <div>
                            <p class="mb-0">Don't have an account? <a href="{% url 'todolist:register' %}"
                                    class="link-primary bold">Sign Up</a>
                            </p>
                        </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


{% if messages %}
<ul>
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
</div>
</body>


{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Register Your Account!</title>
{% endblock meta %}

{% block content %}  

<section class="vh-100 gradient-custom">
    <div class="container-sm py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                <div class="card bg-glass text-white" style="border-radius: 1rem;">
                    <div class="card-body p-5 text-center">
                        <form method="POST" action="">
                            {% csrf_token %}
                                <table class="d-flex">  
                                    {{ form.as_table }}  
                                </table>
                                <button class="btn btn-outline-light btn-lg px-5 mt-5" type="submit">Sign Up</button>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

{% block meta %}
<title>{{user}}'s to-do</title>
{% endblock meta %}

{% block content %}
<nav class="navbar navbar-dark sticky-top">
    <div class="container py-2">
        <a class="navbar-brand text-white" href="#">Welcome, {{user}} &#128075</a>
        <button type="button" class="btn btn-light"><a href="{% url 'todolist:logout' %}"><img
                    src="https://cdn-icons-png.flaticon.com/24/1828/1828427.png"></a></button>
    </div>
</nav>

<body>
    <div class="container-md h-100 overflow-auto justify-content-center align-items-center" id="mainBody">
    </div>

        <div class="card-body p-2 text-center">
            <button class="card-todo sm-2 mb-3 text-white container-sm"><h1><a class="link-primary" data-toggle="modal" data-target="#myModal">+ add</a></h1></button>
        </div>


    <div class="modal fade bg-modal-fade" id="myModal" data-keyboard="false" tabindex="-1" aria-labelledby="myModal"
        aria-hidden="true">

        <h1 class="custom-title py-3 mb-0 m-5 col-lg-5 col-lg-5 col-lg-5">what are you up to?</h1>

        <div class="modal-dialog px-3">
            <div class="modal-content bg-glass p-5 text-center">

                <button type="button" class="btn-close btn-close-white" data-dismiss="modal"
                    aria-label="Close"></button>

                <form method="POST" id="createForm">
                    {% csrf_token %}
                    <div class="mb-md-5">
                        <p class="text-white-50 mb-md-4">stay <u>organized</u>, add a new to-do. </p>

                        <div class="form mb-4">
                            <input type="text" name="title" id="title" placeholder="Task" class="form-control">
                        </div>

                        <div class="form mb-4">
                            <textarea type="text" name="description" id="description" placeholder="Description"
                                class="form-control"></textarea>
                        </div>
                    </div>

                    <button class="btn btn-outline-light btn-lg px-3" type="submit" name="submit" value="Create Task">+
                        Add</button>
                </form>

            </div>
        </div>
    </div>
    </div>
    </div>

</body>

<script>

    $(document).ready(() => {
        let card = todo => `
                    <section class="overflow-auto" id="${todo.pk}">

                            <div class="container-fluid card-todo text-white p-4 md-2">
                                <div class="card-body p-1 text">

                                    ${todo.fields.is_finished ? `<span class="badge rounded-pill bg-success">Done</span> 
                                    <small class="text-white-50"> ${todo.fields.date}<br></small>
                                    <h3 class="card-title bold"> <input type="checkbox" name="check"
                                            onclick="location.href='update_task/${todo.pk}'"
                                            checked />  ${todo.fields.title}</h3>` : `<span class="badge rounded-pill bg-light text-dark">Unfinished</span>
                                    <small class="text-white-50"> ${todo.fields.date}<br></small>
                                    <h3 class="card-title bold"> <input type="checkbox" name="check"
                                            onclick="location.href='update_task/${todo.pk}'" />
                                              ${todo.fields.title}</h3>`}
                                    
                                    <p class="card-text">${todo.fields.description}</p>
                                    <p class="card-text"><a class="link-primary"
                                            href="delete_task/${todo.pk}"> &#10005; Delete
                                            Task</a></p>
                                </div>
                            </div>
                            <br>
                    </section>
        `;

        const getTodo = () => {
            $.get("{% url 'todolist:get_todo_json' %}", data => {
                $.each(data, (i, value) => {
                    $("#mainBody").append(card(value));
                });
            });
        };

        const closeModal = e => {
            $('.modal').removeClass('in');
            $('.modal').attr("aria-hidden", "true");
            $('.modal').css("display", "none");
            $('.modal-backdrop').remove();
            $('body').removeClass('modal-open');
        };

        $("#createForm").submit(e => {

            const csrf_token = document.querySelector(
                "[name=csrfmiddlewaretoken]"
            ).value;
            
            let title = $("#title").val()
            let description = $("#description").val()

            if (title && description) {
                e.preventDefault();

                $.ajax({
                    type: "POST",
                    url: "{% url 'todolist:create_task' %}",
                    headers: { "X-CSRFToken": csrf_token }, 
                    mode: "same-origin",
                    async: true,
                    data: {
                        title: title,
                        description: description,
                    },
                    success: response => {
                        $("#createForm").trigger("reset");
                        $("#mainBody").append(card(response));
                        closeModal();
                    },
                });
            } else {
                alert("Fields cannot be empty!");
            }

        });
        getTodo();
    });

</script>
{% endblock content %}
Footer